language: objective-c
osx_image: xcode9.3
xcode_project: Mnemonic.xcodeproj
xcode_scheme: Mnemonic
xcode_sdk: iphonesimulator9.3
env:
  global:
    - FRAMEWORK_NAME=Mnemonic
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap
script:
    - xcodebuild clean build -sdk iphonesimulator -project Mnemonic.xcodeproj -scheme Mnemonic CODE_SIGNING_REQUIRED=NO
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: pengpengliu/Mnemonic
    tags: true
